### PR TITLE
Fix name shadowing

### LINKED ISSUE #809: Local variable shadows `::name`
In the following code:

```rust
fn name() { unimplemented!() }

#[test]
fn test_name() {
    let name = 1;
    let value = ::name();
}
```

Go to definition on `::name` jumps to the local variable `name`, but it should jump to the function outside.

### PR DESCRIPTION
**Pull request by letmutx**
Attempt to fix #809

### CODE REVIEW

File: src/racer/nameres.rs [hunk 1]
```diff
@@ -861,13 +861,21 @@ pub fn search_crate_root(
     namespace: Namespace,
     session: &Session,
     import_info: &ImportInfo,
+    skip: bool,
```
Comment (kngwyu) [inline src/racer/nameres.rs]: Please use more concrete name, like `skip_this_file` or `skip_if_self_is_mod`.
But, I don't have a good idea now :slightly_frowning_face: , sorry.

File: src/racer/nameres.rs [hunk 2]
```diff
@@ -1819,6 +1838,54 @@ pub fn resolve_path(
...
+    if let Some(context) = context {
+        if path.segments.len() == 1 {
+            let mut v = Vec::new();
+            v.push(context);
+            return v;
+        }
+        let mut new_path = path.clone();
+        new_path.prefix = None;
+        match context.mtype {
+            MatchType::Module => resolve_path(
```
Comment (kngwyu) [inline src/racer/nameres.rs]: Here `MatchType::Crate` can be available so please use `resolve_following_path` here.

File: tests/system.rs [hunk 3]
```diff
@@ -3807,3 +3807,52 @@ fn import_stmt_doesnt_jump_to_closure_arg() {
...
+    let src = r#"
+    fn foo() {
+        let a = ::na~me();
+    }
+"#;
+    let lib = r#"
+    use mod1;
+    pub(crate) fn name() {}
+"#;
+    let (pos, src) = get_pos_and_source(src);
```
Comment (kngwyu) [inline tests/system.rs]: Please use 
```rust
    let dir = TmpDir::new();
    let _lib = dir.write_file("lib.rs");
    let got = get_definition(src, Some(dir));
```

File: src/racer/nameres.rs [hunk 4]
```diff
@@ -1768,6 +1777,16 @@ pub fn resolve_path(
                     return Vec::new();
                 }
             }
+            PathPrefix::Global => {
```
Comment (kngwyu) [inline src/racer/nameres.rs]: :+1:

**Comment by kngwyu** [comment]
I left some comments, but other than that looks great.
Thanks!

File: tests/system.rs (hunk 3 above)
Comment (letmutx) [reply tests/system.rs]: I did use that first and the tests were failing; because `search_crate_root` wasn't able to find the root file.

File: src/racer/nameres.rs (hunk 1 above)
Comment (letmutx) [reply src/racer/nameres.rs]: Me too :) So added a comment where it is used. Would it be better if we change the `modfpath` to an `Option`?

Comment (kngwyu) [reply src/racer/nameres.rs]: Since we use `modfpath` to get parent directory we can't do that.
How about `skip_modfpath`?

**Comment by kngwyu** [comment]
Hi, @letmutx, how is the progress of this PR?
Or, if you're busy, please feel free to let me do the rest work.

**Comment by letmutx** [comment]
I'll not be able to take a look until this weekend. Please continue if you get a chance. Thanks.

**Comment by kngwyu** [comment]
Thank for replaying.
Suddenly I have no time too...
